### ISSUE TITLE
having trouble logging in ... and creating a new account.

### ISSUE THREAD

**Issue by alzinging** [ardriveapp/ardrive-web#1813]
seems like something is broken?

:/

**Comment by alzinging** [comment]
![Screenshot from 2024-08-05 03-52-00](https://github.com/user-attachments/assets/7612a302-d738-4f94-b85c-6e232588fac7)

**Comment by thiagocarvalhodev** [comment]
Hello, @alzinging 

Could you provide more details? The login method e.g. key file, arconnect, metamask? Can you share the logs on the browser console?

**Comment by thiagocarvalhodev** [comment]
Hello @alzinging ,

I wanted to follow up on this issue. Since we haven’t received any additional details or logs, I’m closing this issue for now. If you encounter the problem again, please feel free to reopen the issue with the requested information.
