### ISSUE TITLE
Sync aborts file upload

### ISSUE THREAD

**Issue by Silanael** [ardriveapp/ardrive-web#206]
If a sync occurs while the file picker dialog is open, the upload will not take place after the file is chosen.
The same happens for other functions of the New-menu as well - if the menu is open and sync takes place, the menu choice picked afterwards (such as new folder) will not have an effect.

A rather annoying thing when this happens during navigation towards target file.

**Comment by thiagocarvalhodev** [comment]
This issue was fixed on `v1.4.0`. #300
