### ISSUE TITLE
Missing folders cause drive to fail to load + possibly other issues

### ISSUE THREAD

**Issue by Silanael** [ardriveapp/ardrive-web#228]
Experienced a public drive failing to sync/display due to a missing folder that other folders were referring to.

The drive gets stuck in a state where the loading symbol (on the file display portion, not in the sync dialog) is displayed indefinitely, with no drive data or controls available.

I've observed this to happen in the following filesystem layout:
`Root Folder -> Missing Folder -> Folder 1 (has files) + Folder 2 (has files)`
Only Folders 1 and 2 have files.

The absence of "Missing Folder" confirmed to be the cause of this issue as the problem drive now loads and displays properly after I manually created an ArFS-entity transaction for it.

This behaviour can be reproduced by creating a folder under the drive root folder that points to a Parent-Folder-Id that doesn't exist (using a made-up ID such as 1337babe-511a-dead-beef-ffffffffffff. Don't use that though. It's mine).

Currently, it seems that this issue has been fixed for the code that deals with shared drives (it gracefully displays the orphaned files in the root folder), but is **still present when logged with a wallet that contains the drive**.

Here's an error from an attempt of syncing the problem drive:
![Screenshot from 2021-10-10 17-31-01](https://user-images.githubusercontent.com/81468510/136700890-a9cc1d93-b336-4754-93c6-652db993f08c.png)

***

**It may be that this bug is also behind of an issue of a substantial amount of my private drive files and folders not displaying in ardrive-web** while visible and downloadable by ardrive-cli (fresh install, confirmed to be mined properly). Let me know once you've verified that this bug is fixed and I'll make another issue if this condition still prevails.

**Comment by fedellen** [comment]
> ID such as 1337babe-511a-dead-beef-ffffffffffff 

😂

Can you reproduce this issue within the context of the webapp or just by using manual tools?

**Comment by agsuy** [comment]
Is this still happening?

If so, can you provide a drive ID that replicates the issue?

**Comment by Silanael** [comment]
It would appear that the issue has been successfully fixed.

I couldn't verify this with the original problem drive as I got fed up with waiting and repaired it, but I sought to reproduce the issue on a test drive (Drive ID 17def74f-2e2c-45eb-9e54-53dfb0dd2ba6). This yielded good results with sync working and the orphaned file displayed at the root of the drive.

One curious thing observed was a small discrepancy between logged-in mode and viewing the drive as a shared one - the former doesn't show the orphaned folder the test file is located in, showing the file at the root of the drive, whereas while viewing the drive as a shared one, the orphaned folder was present.

I would consider this as fixed.
