### ISSUE TITLE
Incompatibility with Safari 15

### ISSUE THREAD

**Issue by jdaev** [ardriveapp/ardrive-web#257]
Using the web app on Safari 15 causes it to get stuck after the loading screen. 
It's seems to be an issue with flutter.
To reproduce, attempt to login with any wallet on Safari 15. The app will be stuck at the loading indicator.

**Comment by agsuy** [comment]
Relates to: https://github.com/flutter/flutter/issues/89655

**Comment by agsuy** [comment]
Seems to be fixed on latest version 2.8.1, we re retesting this

**Comment by agsuy** [comment]
Fixes as of 1.4.2

Closing.
