### ISSUE TITLE
bug: home page (app.ardrive.io) crashes after clicking "< go back" window

### ISSUE THREAD

**Issue by akhileshthite** [ardriveapp/ardrive-web#855]
Open `https://app.ardrive.io/` -> select `Don't have a wallet? Get one here!` -> come back to [home](https://app.ardrive.io/) page -> click "< go back" window

The result:
![Screenshot 2023-01-20 at 7 47 36 PM](https://user-images.githubusercontent.com/68826419/213726265-4f2c3d0c-e59c-4ff8-bfeb-2f196e63603f.png)

**Comment by thiagocarvalhodev** [comment]
Thanks for the feedback, @akhileshthite ! 

I can reproduce and we'll create a ticket to address this issue. Any updates on this we'll keep you posted.

**Comment by agsuy** [comment]
Fixed on redesign, closing it.
